### ISSUE TITLE
Cannot access server externally

### ISSUE THREAD

**Issue by elijaha-genvion** [Taisun-Docker/taisun#12]
Hi I still see a blank page when I try to access the server. I already added port 4443 in firewall.
 It's weird because I see this message in remote access tab:  *.taisun.io is accesible on 4443 externally

**Comment by thelamer** [comment]
The remote port check is just using NC to check the port is open on the Wan IP. Admittedly it could be better and look for an http auth request or ssl etc etc. 
Try hitting the local IP and see if you get a cert error in your browser and an auth request IE: 
https://192.168.10.10:4443/

**Comment by thelamer** [comment]
This project has reached EOL.
