### ISSUE TITLE
Support SPICE (HTML5) protocol

### ISSUE THREAD

**Issue by melroy89** [Taisun-Docker/taisun#14]
Support more than just the old RDP protocol (proprietary protocol developed by Microsoft), which is out-dated and slow.

Just like Isard, support also [SPICE](https://en.wikipedia.org/wiki/Simple_Protocol_for_Independent_Computing_Environments) for example or maybe VNC:
https://isardvdi.readthedocs.io/en/latest/user/desktops/#connect-to-viewer

SPICE is fully open-source protocol.

Thanks!

Regards,
Melroy van den Berg

**Comment by thelamer** [comment]
VNC is supported, and at it's core this application uses guacamole and they do not support this protocol: 
https://issues.apache.org/jira/browse/GUACAMOLE-261
RDP might be old, but the world of technology built around it and the feature set for rendering a desktop and remotely sending files/audio is unmatched. 

I looked through some of the repos for spice and their clientside stuff, it looks a little young right now and not ready to implement to have the same feature set. 
I will keep it on my radar though.

**Comment by melroy89** [comment]
SPICE has been open-sourced since 2009: https://en.wikipedia.org/wiki/Simple_Protocol_for_Independent_Computing_Environments

**Comment by thelamer** [comment]
This project has reached EOL.
