### ISSUE TITLE
Missing pieces for the serious self-hoster

### ISSUE THREAD

**Issue by yajo** [Taisun-Docker/taisun#15]
Hi there!

This project rocks. :guitar: 

I'm looking forward to self-host some services on my raspberry and this seems a very good choice. However I see there are some things that seem to be missing, to be able to compete with other projects such as Yunohost or Freedombox:

1. User and group management. It'd be great if Taisun itself could provide user management. Possibly using a simple LDAP server would be enough. Apps could specify in the manifest if they need access to LDAP and Taisun can provide it automatically somehow.
1. Inverse proxy integration. Possibly the natural choice would be Traefik, which connects to the docker socket and autoexposes services on domains and paths depending on container labels. It also handles Let's Encrypt automatically.
1. If one aims to publish services directly, fail2ban would be important too.
1. SSO would be cool too, although LDAP would be enough probably.

So, are there any plans or interest on these subjects?

**Comment by thelamer** [comment]
This project has only ever had code submitted by me, that goes for all server side components and templates. 
It acts as an expression of all of the things I experiment with in Docker. 

There is no reason stuff cannot me implemented to expand it, even your ideas but: 

1. The access management is geared at remote with the assumption that this is running on a local home network with a single port punched in it to allow remote
2. I am on the Linuxserver team and we support a lets encrypt container with this functionality, the custom nodejs based proxy I made is meant as a dead simple remote access method for a single user for situations when they are not on their own network, also the next version of Heimdall will be implementing something like this
3. The remote gateway system by default uses cryptographically secure UUIDs for both the endpoint and authentication passed to the server, someone brute forcing that would be akin to someone brute forcing a Bitcoin private key. I see the value in automating protection for a user, but as you can see by the delayed response here I also do not want to deal with support requests about people being locked out of their own servers. 
4. I do not want to maintain complex databases for users, the entire stack for remote access is already tied to Googles Oauth2

Again anything can be added to this project, I just do not want to always be the sole maintainer and normally I do not implement and support stuff I myself do not personally use.

**Comment by thelamer** [comment]
This project has reached EOL.
