### ISSUE TITLE
Bug with Rocket.chat template deployment

### ISSUE THREAD

**Issue by Danie10** [Taisun-Docker/taisun#18]
If this is not the correct place can someone tell me how I can get into contact with developer/source for the Rocket.chat template in Taisun? I could not find any contact details inside the yml file or elsewhere.

I get this error after deploying below. I have tried going into the mongodb container to activate the replicaset but am also not sure that the rocketchat container is in fact connecting properly to the db one. This template uses default port 3000 which is also the port used by Taisun, so obviously I had to change that before deployment and I chose 3800 which was unused.

Error parsing database URL (undefined)
LocalStore: store created at
LocalStore: store created at
LocalStore: store created at
Setting default file store to GridFS
{"line":"120","file":"migrations.js","message":"Migrations: Not migrating, already at version 211","time":{"$date":1608107928265},"level":"info"}
Loaded the Apps Framework and loaded a total of 0 Apps!
Using GridFS for custom sounds storage
Using GridFS for custom emoji storage
Updating process.env.MAIL_URL
➔ server.js:204 System ➔ error
➔ +---------------------------------------------------------------------------+
➔ | SERVER ERROR |
➔ +---------------------------------------------------------------------------+
➔ | |
➔ | Rocket.Chat Version: 3.9.1 |
➔ | NodeJS Version: 12.18.4 - x64 |
➔ | MongoDB Version: 4.4.2 |
➔ | MongoDB Engine: wiredTiger |
➔ | Platform: linux |
➔ | Process Port: 3000 |
➔ | Site URL: http://localhost:3000 |
➔ | ReplicaSet OpLog: Disabled |
➔ | Commit Hash: 798241b9e5 |
➔ | Commit Branch: HEAD |
➔ | |
➔ | OPLOG / REPLICASET IS REQUIRED TO RUN ROCKET.CHAT, MORE INFORMATION AT: |
➔ | https://go.rocket.chat/i/oplog-required |
➔ | |
➔ +---------------------------------------------------------------------------+

**Comment by thelamer** [comment]
This project has reached EOL.
