### ISSUE TITLE
Timezones

### ISSUE THREAD

**Issue by Sblop** [Taisun-Docker/taisun#2]
I can see you try to limit the number of timezones, which I generally think is fine... Hoever I live in mainland Europe, and for this reason timezone for London is not sufficient.

**Comment by thelamer** [comment]
These are just example templates and not supposed to be an end all. 
Anyone with a GitHub account can upload and share stacks https://stacks.taisun.io/ .

https://github.com/Taisun-Docker/taisun/wiki/Templates

But I can go back through and add in a couple more to the ones I have uploaded .

**Comment by thelamer** [comment]
Got me thinking though I should give people the ability to edit templates locally before launching , will add this functionality

**Comment by thelamer** [comment]
@Sblop I have added a few more European timezones to my personal templates and added the ability to edit templates in the web UI so users can define whatever they want from other users stacks.
