### ISSUE TITLE
Event error

### ISSUE THREAD

**Issue by knkrth** [Taisun-Docker/taisun#5]
While running taisun locally I got event error,

```
taisun$ sudo node app.js 
listening on *:3000
RrZ32dp4VPwaKyiWAAAA connected time=1568908721106
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn unbuffer ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by thelamer** [comment]
What version of node.js ? Did you run an npm install before running the application ?

I only test this against the docker container it runs in and do not officially support any version of nodes outside of that.

**Comment by knkrth** [comment]
Ya, I build docker image locally & everything works fine on the docker but not on the local environment. I did `sudo npm install` & run `sudo node app.js`

I use,
```
node v10.16.3
npm 6.9.0
```

**Comment by knkrth** [comment]
The older version create the cloud9 container & If I hit launch it launches the cloud9 container immediately. 

But on the latest build when I click on launch container after creating it. It redirect me to the designated URL & Says 
![image](https://user-images.githubusercontent.com/12738581/65264036-65d44e80-db2b-11e9-9703-3fefd9cf7106.png)
After 10 seconds only connection established.

**Comment by thelamer** [comment]
This app really is designed with docker in mind, if you are looking to play with the code might I suggest the development container for it ? 

`taisun/webapp:latest.dev`

This is built off the latest master commit and if you forward port 8000 there is cloud9 baked in. 
The current lean docker logic is all in the linuxserver repo now :+1: 
https://github.com/linuxserver/docker-taisun

**Comment by knkrth** [comment]
Ok, Thanks for your help.
